name: Verify

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.300
    - name: Install dependencies
      run: dotnet restore
    - name: Build, test and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        dotnet build --configuration Release --no-restore
        dotnet build --configuration Debug --no-restore
        dotnet test --configuration Debug --no-build --verbosity normal --logger:trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
